# Generated by Django 4.0 on 2021-12-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_demot_image_demot_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demot',
            name='image',
            field=models.ImageField(blank=True, default='cat.jpg', null=True, upload_to=''),
        ),
    ]
