# Generated by Django 4.0 on 2021-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_demot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='demot',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demot',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
