# Generated by Django 4.0 on 2021-12-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_ips_demot_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demot',
            name='ip',
        ),
        migrations.AddField(
            model_name='demot',
            name='ips',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ips',
        ),
    ]
