# Generated by Django 4.0 on 2022-01-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_demot_ip_demot_ips_delete_ips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('demot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.demot')),
            ],
        ),
    ]
